---
name: Compile Unix Library (arm64)

description: |
  Prepare and compile unix builds for arm64 cpus

inputs:
  compiler:
    required: true
    description: Compiler to use
  dockerimage:
    required: false
    description: "the base os image to run in arm64 mode. see https://github.com/uraimo/run-on-arch-action#supported-platforms"
    default: ubuntu20-04

runs:
  using: composite
  steps:

    - name: Compile
      uses: ./.github/actions/run-on-linux-aarch64
      with:
        dockerimage: ${{ inputs.dockerimage }}
        compiler: ${{ inputs.compiler }}
        run: make test

