---
name: Compile Unix Library (x64)

description: |
  Prepare and compile unix builds for x64 cpus

inputs:
  compiler:
    required: true
    description: Compiler to use

runs:
  using: composite
  steps:

    - name: Prepare
      env:
        CC: ${{ inputs.compiler }}
      shell: bash
      run: |
        cc --version
        git clone https://github.com/Conni2461/examiner
        cd examiner
        make && sudo make install

    - name: Build
      env:
        CC: ${{ inputs.compiler }}
        LD_LIBRARY_PATH: /usr/lib:/usr/local/lib
      shell: bash
      run: make
